### ISSUE TITLE
Looping theme.mp3

### ISSUE THREAD

**Issue by servusdei2018** [servusDei2018/TankistOnline#2]
Currently, the game's themesong is started by

```python
		global theme
		
		theme = vlc.MediaPlayer("sfx/theme.mp3")
		theme.play()
```

but when the song finishes, it doesn't loop.

**Feel free to push a fix to the beta branch.**

**Comment by servusdei2018** [comment]
Issue fixed, thankyou @edbucks.

**Comment by edbucks** [comment]
Pleasure!
