### ISSUE TITLE
Update `TankistOnline_Server.py` to Python 3

### ISSUE THREAD

**Issue by servusdei2018** [servusDei2018/TankistOnline#7]
The server-side code needs to be updated to Python 3.

**Comment by GMLeah** [comment]
you still doing this project? i want to help

**Comment by servusdei2018** [comment]
@GMLeah , yep, I'm still doing this project, but I'm sorry to say that development has lagged in the past months due to me having a heavy workload at work -- so I can't make much contributions atm. However, feel free to push changes and I'll review and approve them.

**Comment by GMLeah** [comment]
@servusDei2018  no worries :) share here actually. i got some small free time especially weekends. cheers.

**Comment by servusdei2018** [comment]
@GMLeah Sounds great. So I plan to add a scrolling background to the client next, then rework the server-side code (it's pretty sloppy atm).

**Comment by GMLeah** [comment]
i managed to run in pycharm. excellent work. ill try to explore like adding controllers simultaneously click move button while rotating. option to use W S A D instead of arrow keys.  left and right button so fast xD. this good for my learning in python :)

**Comment by servusdei2018** [comment]
I'm glad you like it :D I've updated the project, and now the server is running and the client can connect to it (but is far from complete).

**Comment by servusdei2018** [comment]
Ok, server is now Python3 and backwards compatible to Python2 or PyPy. For further collaboration, please refer to #4
